config/routes.rb
# -*- encoding : utf-8 -*-
Yl::Application.routes.draw do
  themes_for_rails

  constraints(CoSubdomain) do
    root to: "companies#home"
  end
  constraints :subdomain => 'c' do
    root to: "companies#index"
    get '/p-:id' => "companies#province",as: "province"
    resources :companies,path: '' do
      get :all,on: :collection
    end
  end


  get "settings/index"

  resources :shops,path: "yaodian" do
    get "redirect",on: :member
  end


  resources :options


  resources :jibings,:path=>'jibing' do
    member do 
      get 'suggest'
    end
  end

  match "/goto/:class_name/:id"=>'home#goto'
  resources :comments,:only=>%w(index create show)

  resources :entries,:path=>'zhaoshang' do
    collection do 
      get :hot
    end
  end
  match '/archive/:date'=>'home#date',:as=>'date'
  match '/archive'=>'home#archive',:as=>'archive'

  resources :posts,:path=>"news"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "tools/adsense"
  get "tools/adsense_preview"
  match '/gad'=>'tools#adsense'

  resources :links do
    collection do
      get :manage
    end
  end

  match '/category/:category_id'=>'drugs#category',:as=>"category"
  resources :chengfens,:path=>'chengfen' , :only=>[:index,:show] do
    get :shouzi,:on=>:collection
  end

  resources :categories do
    collection do
      get :manage
    end
  end

  # match '/chengfen/:name'=>"yaopins#chengfen",:as=>"chengfen"



  # match '/yaoming/:name'=>"yaopins#name",:as=>"name"
  match '/jixing/:jixing'=>"yaopins#jixing",:as=>"jixing"
  match '/leibie/:leibie'=>"yaopins#leibie",:as=>"leibie"
  resources :yaopins,:path=>'pihao' do
    collection do
      get :manage
      get :auto_complete
      get :search
      get :map
    end
    member do
      post :track
    end
  end

  # authenticated :user do
    # root :to => 'home#index'
  # end

  devise_for :users
  resources :users, :only => [:show, :index]
  get '/profile/edit'=>"users#edit_profile",:as=>'edit_profile'
  put '/profile'=>"users#update_profile",:as=>'update_profile'
  match '/:id/%e8%af%b4%e6%98%8e%e4%b9%a6'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  match '/:id/%E8%AF%B4%E6%98%8E%E4%B9%A6'=>"drugs#shuomingshu"
  resources :drugs,:path=>'yaopin' do
    collection do
      get :manage
      get :shouzi
      get :search
      get :desc
      get :desc_preview
    end
    member do
      get :pihao
      post :track
      # get :shuomingshu
    end
  end

  match '/bdapp(/:action(/:id))'=>"bdapp"
  match 'sitemap' => 'home#sitemap'
  match 'flush' => 'home#flush'
  match 'index' => 'home#index'
  match 'redirect' => 'home#redirect',as: 'redirect'
  match ':action' => "home",:constraints=>{:action=>/sitemap|flush|souyao|stats|mmseg|test|redirect|chaxun/}
  resque_constraint = lambda do |request|
    Rails.env.development? or 
    (request.env['warden'].authenticate? and
      request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    match '/settings(/:action(/:id))'=>"settings"
    mount Resque::Server.new, :at => "/resque"
  end
  #match '/(ask|wiki)/:id' => "posts#show",as: "po"
  match '/:act/:id' => "posts#show",:constraints=>{:act=>/news|ask|wiki/},as: :po
  #match '/ask/:id' => "posts#show",as: :ask
  #match '/wiki/:id' => "posts#show",as: :wiki

  match '/:id'=>"drugs#show",:as=>"show_yao"

  #match '/:id/说明书'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  root :to => "home#index"
match "syncs/:type/new" => "syncs#new", :as => :sync_new
match "syncs/:type/callback" => "syncs#callback", :as => :sync_callback

end

app/models/shop.rb
#encoding: utf-8
class Shop < ActiveRecord::Base
  attr_accessible :address, :affurl, :cert, :company_name, :domain, :expires_in, :linked, :name, :owner, :reg_in, :service, :website,:nicename,
    :pr,:br,:alexa, :priority
  validates :name,presence: true
  validates :website,presence: true
  def self.import(data)
    if !exists?(cert: data[:cert])
      create(data)
    end
  end
  def url
    affurl.present? ?
      affurl :
        (linked? ? website : "/yaodian/#{id}/redirect")
  end
  def nofollow?
    affurl.present? or !linked?
  end
  def rel
    nofollow? ? {rel: 'nofollow'} : {}
  end
  def as_json options={}
    self[:domain] = website.sub('http://','').sub(/^www./,'')
    self[:br] ||= -1
    self[:pr] ||= -1
    self[:alexa] ||= 999999999
    #self[:nicename] = name.truncate(10)
    options = {only: %w(name affurl website domain cert reg_in expires_in id pr br alexa)}.merge(options)
    super
  end
  def self.update_all_ranks
    where(alexa: nil).find_each do |r|
      ranks = PageRankr.ranks(r.website.sub('http://',''),
        :google,:baidu,:alexa_global) rescue nil
      next if ranks.nil?
      r.update_attributes(pr: ranks[:google],
                          br: ranks[:baidu],
                          alexa: ranks[:alexa_global])
    end
  end
  class Sfda < Yaopin::Sfda
    def initialize table
      @table = table
      @url = 'http://app1.sfda.gov.cn/datasearch/face3/'
    end
    def async_get_item table,id
      get_item id
    end
    def get_list id
      super @table,id
    end
    def process start=1
      get_list start
      i = start + 1
      while i <= @total_page
        get_list i
        i+=1
      end
    end
    def get_item id
      doc = get_doc (@url + "content.jsp?tableId=#{@table}&tableName=TABLE#{@table}&Id=#{id}")
      ignores = %w(邮编 IP地址)
      data = {}
      keys = {
        "证书编号"=>:cert,
         "服务范围"=>:service,
         "单位名称"=>:company_name,
         "发证日期"=>:reg_in,
         "有效截至日期"=>:expires_in,
         "法定代表人"=>:owner,
         "单位地址"=>:address,
         "网站名称"=>:name,
         "域名"=>:domain,
      }
      doc.css('table[align=center] tr').each do |tr|
        td2 = tr.css('td')[1]
        next if td2.nil?
        key = tr.css('td')[0].text
        next if ignores.include? key
        val = td2.text.strip
        next if val.blank?
          
        if keys.has_key? key
          data[keys[key]] = val
        end
      end
      data[:domain] = 'www.yaofangwang.com' if data[:domain].nil? && data[:cert] == '国A20110001'
      if data[:domain].present?
        data[:domain].gsub!('http://','')
        website = data[:domain].match(/[\w\d\-\.]+/i)[0]
        website = "www."+ website if website[0,4] != 'www.'
        data[:website] = "http://" + website
      end
      data[:name].gsub!(/\s/,'')
      Shop.import(data)
    end
  end
end

app/controllers/shops_controller.rb
#encoding: utf-8
class ShopsController < ApplicationController
  load_and_authorize_resource :except=>%w(redirect)
  before_filter :_noad

  def _noad
    @hide_subnav = true
    @js = "shops"
    @ng_app = "Shops"
    @title_suffix = "_网上药店排名"
    breadcrumbs.add "网上药店",action_name == "index" ? nil : shops_url
    super
  end
  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.order('isnull(alexa) asc,alexa asc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { 
        q = "%#{params[:q]}%"
        @shops = @shops.
          where("name like ? or domain like ? or cert like ?",q,q,q) if params[:q].present?
        render json: @shops 
      }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])
    breadcrumbs.add @shop.name,nil

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shop }
    end
  end
  def redirect
    @shop = Shop.find(params[:id])
    redirect_to @shop.website,status: 301
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
    @shop = Shop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shop }
    end
  end

  # GET /shops/1/edit
  def edit
    @shop = Shop.find(params[:id])
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render json: @shop, status: :created, location: @shop }
      else
        format.html { render action: "new" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])

    respond_to do |format|
      if @shop.update_attributes(params[:shop])
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.haml
= simple_form_for(@shop) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :website
    = f.input :domain
    = f.input :pr
    = f.input :br
    = f.input :alexa
    = f.input :affurl
    = f.input :linked
    = f.input :cert
    = f.input :company_name
    = f.input :service
    = f.input :owner
    = f.input :address
    = f.input :reg_in
    = f.input :expires_in

  .form-actions
    = f.button :submit

app/views/shops/_list.html.haml
%table.table{"ng-hide"=>"hide_table"}
  %tr
    %th
    -%w(name website pr br alexa cert reg_in).each do |k|
      %th{class: k == "alexa" ? "text-right" : ""}
        =t("shop.#{k}")

  - @shops.each_with_index do |shop,i|
    %tr
      %td= i + 1
      %td= link_to shop.name.truncate(12),shop_url(shop),title: "#{shop.name}"
      %td= link_to shop.website.sub('http://','').sub(/^www\./,''),shop.url,{target: "_blank",class: "external"}.merge(shop.rel)
      %td
        .rank.rank-pr= shop.pr || '-'
      %td
        .rank.rank-br= shop.br || '-'
      %td.text-right= shop.alexa? ? number_with_delimiter(shop.alexa) : '-'
      %td= shop.cert
      %td= shop.expires_in

app/views/shops/edit.html.haml
%h1 Editing shop

= render 'form'

= link_to 'Show', @shop
\|
= link_to 'Back', shops_path

app/views/shops/index.html.haml
-title "网上药店排名_中国十大正规网络药店/网上平价买药购药/网上药店哪个好",nil,false
-meta :keywords,"网上药店,药店,网上药店排名,买药网,网上购药,网络药店,药店网,网络药店,网上十大正规药店,中国最大网上药店,平价药店"
-meta :description,t('.description')
-@title_suffix = ""
-@col1 = true

-content_for :banner do
  =ubaidu 1470606,"药店频道首页960*90，创建于2014-2-17" 
  .mt1e
    .leftlinks
      =ubaidu 1470620,"药店频道左侧头部链接620*160，创建于2014-2-17"
    .righttext
      .well
        %strong 网上药店频道介绍
        =t('.description')
    .clearfix
%h1
  网上药店排名
%div{"ng-controller"=>"ShopsCtrl"}
  .form-inline.form-filter.hide-on-ie6
    %label 在名称/网址/许可证中搜索&nbsp;
    %input{"ng-model"=> "shopq",type: "text"}
  -if is_ie6?
    .alert
      %span.text-error 你使用的是IE6浏览器，以下表格的筛选、排序功能将无法启用。
    -#%input{"ng-model"=> "shopq",type: "text","ng-change"=>"search()"}
  = render :partial => 'list'
  %table.table.table-bordered-bottom.hide-on-ie6{"ng-show"=>"hide_table"}
    %tr
      %th
      -%w(name website pr br alexa cert reg_in).each do |k|
        %th{class: k == "alexa" ? "text-right" : ""}
          -if %(pr br).include? k
            -asc = ""
            -desc = '-'
          -else
            -asc = "-"
            -desc = ''
          <a href="" ng-click="predicate = '#{desc}#{k}'" ng-hide="predicate == '#{desc}#{k}'">#{t("shop.#{k}")}</a>
          <a href="" ng-click="predicate = '#{asc}#{k}'" ng-show="predicate == '#{desc}#{k}'">#{t("shop.#{k}")}</a>
          <a href="" ng-click="predicate = '#{k}'" ng-show="predicate == '-#{k}'">&or;</a>
          <a href="" ng-click="predicate = '-#{k}'" ng-show="predicate == '#{k}'">&and;</a>

    %tr{"ng-repeat"=>"shop in shops|filter:shopq |orderBy:predicate"}
      %td {{$index + 1}}
      %td
        %a{href: "/yaodian/{{shop.id}}",title: "{{shop.name}}",target: "_blank"} {{shop.name|truncate}}
      %td
        %a{href: "{{shop.affurl || shop.website}}",'ng-click'=> "track(shop.domain)",title: "访问官网",target: "_blank"} {{shop.domain}}
      %td
        .rank.rank-pr {{shop.pr == -1 ? "-" : shop.pr}}
      %td
        .rank.rank-br {{shop.br == -1 ? "-" : shop.br}}
      %td.text-right {{shop.alexa == 999999999 ? "-" : (shop.alexa|number)}}
      %td {{shop.cert}}
      %td {{shop.reg_in}}

  -#= link_to 'New Shop', new_shop_path

-content_for :foot do
  %h2 网上药店大全
  %p.description=sprintf("本站网上药店导航频道为你提供获得互联网药品交易服务资格证的%d家正规<strong>网上药店</strong>列表，相应网上药店网站PR、权重及排名信息，方便用户排序、筛选，据此判断网上药店哪家好，作为您网上买药购药的参考。",209).html_safe

app/views/shops/new.html.haml
-title "提交药店"
= render 'form'

= link_to '返回', shops_path

app/views/shops/show.html.haml
-title "#{@shop.name}_#{@shop.name}怎么样/点评",nil,false
-meta :keywords,t('.keywords',name: @shop.name)
-meta :description,t('.description',name: @shop.name,cert: @shop.cert)
-@spans = 8
-content_for :banner do
  =ubaidu 1470606,"药店频道首页960*90，创建于2014-2-17" 
-content_for :before_links do
  =ubaidu 1470651,"药店单页左上链接610*140，创建于2014-2-17"
%h1=@shop.name
%ul.unstyled.attrs
  %li
    %b 官方网站:
    = link_to @shop.website,@shop.url,{target: "_blank",onclick: "_hmt.push(['_trackEvent','yaodian','show','#{@shop.domain}'])"}.merge(@shop.rel)
  %li
    %b 
      %abbr{title: "互联网药品交易服务资格证"} 资格证号
    = @shop.cert
  %li
    %b 公司名称:
    = @shop.company_name
  %li
    %b 服务范围:
    = @shop.service
  %li
    %b 法人:
    = @shop.owner
  %li
    %b 注册地址:
    = @shop.address
  %li
    %b 注册域名:
    = @shop.domain
  %li
    %b 审批日期:
    = @shop.reg_in
  %li
    %b 到期日期:
    = @shop.expires_in

-if can? :edit,@shop
  = link_to 'Edit', edit_shop_path(@shop)
  \|
= link_to '返回', shops_path
-content_for :foot do
  %h2 #{@shop.name}介绍
  %p.description=sprintf("%1$s是由国家食品药品监督局颁发互联网药品交易服务资格证的正规网上药店，资格证号为%2$s。",@shop.name,@shop.cert).html_safe
  %h3 #{@shop.name}相关药店
  -token = Digest::MD5.hexdigest(request.url)[0,2]
  -cache "related-shops-#{token}" do
    -shops = Shop.order("rand()").limit(42)
    %p.links
      -shops.each do |shop|
        =link_to shop.name.truncate(10),shop,title: shop.name