config/routes.rb
# -*- encoding : utf-8 -*-
Yl::Application.routes.draw do
  themes_for_rails

  constraints(CoSubdomain) do
    root to: "companies#home"
  end
  constraints :subdomain => 'c' do
    root to: "companies#index"
    get '/p-:id' => "companies#province",as: "province"
    resources :companies,path: '' do
      get :all,on: :collection
    end
  end


  get "settings/index"

  resources :shops,path: "yaodian" do
    get "redirect",on: :member
  end


  resources :options


  resources :jibings,:path=>'jibing' do
    member do 
      get 'suggest'
    end
  end

  match "/goto/:class_name/:id"=>'home#goto'
  resources :comments,:only=>%w(index create show)

  resources :entries,:path=>'zhaoshang' do
    collection do 
      get :hot
    end
  end
  match '/archive/:date'=>'home#date',:as=>'date'
  match '/archive'=>'home#archive',:as=>'archive'

  resources :posts,:path=>"news"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "tools/adsense"
  get "tools/adsense_preview"
  match '/gad'=>'tools#adsense'

  resources :links do
    collection do
      get :manage
    end
  end

  match '/category/:category_id'=>'drugs#category',:as=>"category"
  resources :chengfens,:path=>'chengfen' , :only=>[:index,:show] do
    get :shouzi,:on=>:collection
  end

  resources :categories do
    collection do
      get :manage
    end
  end

  # match '/chengfen/:name'=>"yaopins#chengfen",:as=>"chengfen"



  # match '/yaoming/:name'=>"yaopins#name",:as=>"name"
  match '/jixing/:jixing'=>"yaopins#jixing",:as=>"jixing"
  match '/leibie/:leibie'=>"yaopins#leibie",:as=>"leibie"
  resources :yaopins,:path=>'pihao' do
    collection do
      get :manage
      get :auto_complete
      get :search
      get :map
    end
    member do
      post :track
    end
  end

  # authenticated :user do
    # root :to => 'home#index'
  # end

  devise_for :users
  resources :users, :only => [:show, :index]
  get '/profile/edit'=>"users#edit_profile",:as=>'edit_profile'
  put '/profile'=>"users#update_profile",:as=>'update_profile'
  match '/:id/%e8%af%b4%e6%98%8e%e4%b9%a6'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  match '/:id/%E8%AF%B4%E6%98%8E%E4%B9%A6'=>"drugs#shuomingshu"
  resources :drugs,:path=>'yaopin' do
    collection do
      get :manage
      get :shouzi
      get :search
      get :desc
      get :desc_preview
    end
    member do
      get :pihao
      post :track
      # get :shuomingshu
    end
  end

  match '/bdapp(/:action(/:id))'=>"bdapp"
  match 'sitemap' => 'home#sitemap'
  match 'flush' => 'home#flush'
  match 'index' => 'home#index'
  match 'redirect' => 'home#redirect',as: 'redirect'
  match ':action' => "home",:constraints=>{:action=>/sitemap|flush|souyao|stats|mmseg|test|redirect|chaxun/}
  resque_constraint = lambda do |request|
    Rails.env.development? or 
    (request.env['warden'].authenticate? and
      request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    match '/settings(/:action(/:id))'=>"settings"
    mount Resque::Server.new, :at => "/resque"
  end
  #match '/(ask|wiki)/:id' => "posts#show",as: "po"
  match '/:act/:id' => "posts#show",:constraints=>{:act=>/news|ask|wiki/},as: :po
  #match '/ask/:id' => "posts#show",as: :ask
  #match '/wiki/:id' => "posts#show",as: :wiki

  match '/:id'=>"drugs#show",:as=>"show_yao"

  #match '/:id/说明书'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  root :to => "home#index"
match "syncs/:type/new" => "syncs#new", :as => :sync_new
match "syncs/:type/callback" => "syncs#callback", :as => :sync_callback

end

app/models/yaopin.rb
# -*- encoding : utf-8 -*-
#encoding: utf-8
class Yaopin < ActiveRecord::Base
  attr_accessible :benweima, :benweima_beizhu, 
    :changjia_dizhi, :changjia_name, :changjia_guojia, 
    :en, :guige, :jixing, :leibie, :name, :shangpin_name, 
    :wenhao, :yuanwenhao, :pizhunri,:daoqiri,:meta,
    :drug_id,:found_at, :company_id
  resourcify
  belongs_to :drug,:counter_cache=>true
  belongs_to :company,:counter_cache=>true
  has_many :items
  
  # default_scope order("wenhao asc")
  scope :wenhao_order,order("wenhao asc")
  scope :newest,order("id desc")
  scope :inlist,select('id,wenhao')
  acts_as_commentable
  
  define_index do
    indexes :name,:shangpin_name,:wenhao,:changjia_name,:yuanwenhao,:en
    has :jixing,:leibie
    has :created_at
    has :daoqiri,:pizhunri
  end
  sphinx_scope :fullscan do {:match_mode=>:fullscan} end
  sphinx_scope :slimit do |num| {:per_page=>num} end
  sphinx_scope :by_changjia do |name|
    {:conditions=>{:changjia_name=>name}}
  end
  #sphinx_scope : {:match_mode=>:fullscan}
  def to_param
    wenhao.present? ? wenhao : id
  end
  def wenhao_and_name
    "#{wenhao} / #{name}"
  end
  class << self
    def find *args
      return find_by_wenhao(args[0]) if args.size == 1 and args[0].is_a? String
      super
    end
    def all_leibie
      Rails.cache.fetch "all-leibie" do
        Yaopin.group(:leibie).pluck(:leibie)
      end
    end
    def test
      n = 100
      limit = 50
      Benchmark.bm(7) do |x|
        #x.report("search:") { n.times {|i| Yaopin.search(:order=>'@random',:per_page=>limit).all } }
        #x.report("id shuffle:")  { n.times {|i| Yaopin.random_by_id_shuffle(limit) } }
        x.report("Jibing random")  { n.times {|i| Jibing.order("rand()").limit(limit).all } }
        x.report("Jibing shuffle")  { n.times {|i| Jibing.random_by_id_shuffle(limit) } }
      end
    end
  end
  class Sfda
    #include Resque::Plugins::Async::Method
    @queue = :sfda
    def self.perform method,*args
      self.new.send method,*args
    end
    def async_get_list table,page
      Resque.enqueue Yaopin::Sfda,:get_list,table,page
    end
    def async_get_item table,id
      Resque.enqueue Yaopin::Sfda,:get_item,table,id
    end
    def initialize
      @url = 'http://app1.sfda.gov.cn/datasearch/face3/'
    end
    def run
      # get_table 25,s
      get_table_lists 25,11097
      # get_table 36
    end
    def process start=1
      get_list 25,start
      i = start + 1
      while i <= @total_page
        async_get_list 25,i
        i+=1
      end
    end
    def get_table table,page=1
      begin
        rs = get_list(table,page)
        page += 1
        puts page
      end while rs
    end
    def get_table_lists table,pages,page=1
      while page <= pages
        get_list(table,page)
        #delay(:priority=>10).get_list(table,page)
        page+=1
      end
    end
    def get_list(table,page=1)
      doc = get_doc(@url + "search.jsp?tableId=#{table}&curstart=#{page}") 
      #doc = get_doc(@url + "base.jsp?tableId=#{table}&curstart=#{page}") 
      @total_page ||= doc.text.match(/共(\d+)页 共\d+条/)[1].to_i
      #pp doc if Rails.env.test?
      #todo: 检查药品是否存在
      doc.css('p[align=left] a').each do |node|
        wenhao = node.text().match(/国药.字(\w\d+)/)[0] rescue nil
        next if wenhao.nil?
        next if Yaopin.exists?(wenhao: wenhao)
        ms = node.attr("href").match(/tableId=(\d+).+?Id=(\d+)/)
        next if ms.nil?
        #delay.get_item ms[1],ms[2]
        async_get_item ms[1],ms[2]
        # break
      end
    end
    def search keyword
      doc = get_doc(@url + "search.jsp?tableId=25&keyword=#{CGI.escape(keyword)}") 
      doc.css('p[align=left] a').each do |node|
        ms = node.attr("href").match(/tableId=(\d+).+?Id=(\d+)/)
        next if ms.nil?
        #delay.get_item ms[1],ms[2]
        get_item ms[1],ms[2]
        # break
      end
    end
    def get_item table,id
      doc = get_doc (@url + "content.jsp?tableId=#{table}&tableName=TABLE#{table}&Id=#{id}")
      data = {:meta=>{}}
      ignores = %w(相关数据库查询 注)
      ignores << ""
      if table.to_i == 25
        data[:changjia_guojia] = "中国"
        keys = {
          "批准文号"=>:wenhao,
           "原批准文号"=>:yuanwenhao,
           "药品本位码"=>:benweima,
           "药品本位码备注"=>:benweima_beizhu,
           "产品名称"=>:name,
           "英文名称"=>:en,
           "商品名"=>:shangpin_name,
           "生产单位"=>:changjia_name,
           "生产地址"=>:changjia_dizhi,
           "规格"=>:guige,
           "剂型"=>:jixing,
           "产品类别"=>:leibie,
           "批准日期"=>:pizhunri
        }
      else
        keys = {
          "注册证号"=>:wenhao,
           "原注册证号"=>:yuanwenhao,
           "药品本位码"=>:benweima,
           "药品本位码备注"=>:benweima_beizhu,
           "产品名称（中文）"=>:name,
           "产品名称（英文）"=>:en,
           "商品名（中文）"=>:shangpin_name,
           "生产厂商（英文）"=>:changjia_name,
           "厂商国家（中文）"=>:changjia_guojia,
           "厂商地址（英文）"=>:changjia_dizhi,
           "规格（中文）"=>:guige,
           "剂型（中文）"=>:jixing,
           "产品类别"=>:leibie,
           "发证日期"=>:pizhunri,
           "有效期截止日"=>:daoqiri,
        }
      end
      doc.css('table[align=center] tr').each do |tr|
        td2 = tr.css('td')[1]
        next if td2.nil?
        key = tr.css('td')[0].text
        next if ignores.include? key
        val = td2.text.strip
        next if val.blank?
          
        if keys.has_key? key
          data[keys[key]] = val
        else
          data[:meta][key] = val
        end
      end
      
      (Rails.logger.debug "get_list:wenhao null #{[table,id]}" and return) if data[:wenhao].nil?
      drug = Drug.where(:name=>data[:name]).first_or_create(:en=>data[:en])
      data[:drug_id] = drug.id
      data[:found_at] = Time.now
      r = Yaopin.where(:wenhao=>data[:wenhao]).first
      if r.nil?
        r = Yaopin.create data
        Rails.logger.tagged("Yaopin New"){
          Rails.logger.debug [r.id,r.wenhao,r.pizhunri]
        }
      else
        r.update_attributes data
        Rails.logger.debug ["Exists",r.id,r.wenhao,r.pizhunri]
      end
      if data[:changjia_name].present? && data[:changjia_name] != '----'
        company = Company.where(name: data[:changjia_name]).first_or_create(address: data[:changjia_dizhi])
        r.company = company
        r.save
      end
      r
    end
    #async_method :get_list#,:get_item
    def get_doc url
      Rails.logger.debug "curl:#{url}"
      res = Typhoeus::Request.get(url)
      Nokogiri::HTML(res.body)
    end
  end
end

app/controllers/yaopins_controller.rb
# -*- encoding : utf-8 -*-
class YaopinsController < ApplicationController
  load_and_authorize_resource :except=>%w(name jixing leibie auto_complete search track map)

  has_mobile_fu
  has_mobile_fu_for :index,:leibie,:search
  caches_action :index,:search,:show,:expires_in => 1.day, :if => Proc.new { flash.count == 0 },:cache_path => Proc.new{ params}
  before_filter :init_breadcrumbs#,:except=>[:show]

  # GET /yaopins
  # GET /yaopins.json
  def index
    @yaopins = Yaopin.order("id desc").page(params[:page]).per(params[:per] || 100)
    if params[:name].present?
      @yaopins = @yaopins.where(:name=>params[:name])
    end

  end
  def map
    respond_to do |format|
      format.html {
        @yaopins = Yaopin.page(params[:page] || 1).per(params[:per] || 500).select(%w(id wenhao))
        breadcrumbs.add "第#{params[:page]}页",nil if params[:page]
      }
      format.xml {
        @yaopins = Yaopin.page(params[:page] || 1).per(params[:per] || 5000).select(%w(id wenhao))
        
      }
    end
  end
  def track
    @yaopin = Yaopin.where(:id=>params[:id]).first
    request.env["HTTP_REFERER"] = CGI.unescape(params["referer"])
    track_page_view(@yaopin)
    render :nothing=>true
  end
  def search
    @q = params[:q]
    @qby = :pihao
    if @q.match(/[a-z0-9]/i)
      @yaopins = Yaopin.where(["name like ? or wenhao like ?","%#{params[:q]}%","%#{params[:q]}%"]).page(params[:page] || 1).per(20)
    else
      @yaopins = Yaopin.search @q,
          :per_page=>20, :page=>params[:page] || 1
    end
    @title="搜索\"#{@q}\""
    @hide_leibie = true
    breadcrumbs.add "搜索\"#{@q}\""
  end
  def auto_complete
    @term = params[:term]
    if @term.match(/[a-z0-9]/i)
      @topics = Yaopin.select([:name,:wenhao]).where("wenhao like ?","%#{@term}%").limit(10).all
    else
      @topics = Yaopin.search @term,:per_page=>10
    end
    if @topics.present?
      @results = @topics.collect do |t|
        #{:label=>"#{t.wenhao}<small>#{t.name}</small>",:value=>show_yao_url(t.name)}
        {:label=>"#{t.wenhao}/#{t.name}",:value=>yaopin_url(t)}
      end
      @results << {:label=>"共#{@topics.total_entries}项结果",:value=>search_yaopins_url(:q=>@term)} if @topics.respond_to? :total_entries
    else
      @results = [{:label=>t('auto_complete.not_found'),:value=>0}]
    end
    render :json => @results.to_json
  end
  def auto_complete_ar
    @term = params[:term]
    if @term =~ /[国药准字A-Z0-9a-z]/
      @topics = Yaopin.select([:name,:wenhao]).where(["name like ? or wenhao like ?","%#{params[:term]}%","%#{params[:term]}%"]).limit(10).collect{|t|
        {:label=>[t.wenhao,t.name].join('/'),:value=>yaopin_url(t)}
      }
      else
      @topics = Drug.select([:name,:en]).where(["name like ?","%#{params[:term]}%"]).limit(10).collect{|t|
        {:label=>[t.name,t.en].join('/'),:value=>show_yao_url(t.name)}
      }
    end

    if @topics.empty?
        render :json => [{:label=>t('auto_complete.not_found'),:value=>0}].to_json
      else
        render :json => @topics.to_json
    end

  end
  def name
    @yaopins = Yaopin.where(:name=>params[:name]).page(params[:page] || 1).per(100)
    @hide_yaoming = true
    @title = params[:name]

    breadcrumbs.add :name,nil
    breadcrumbs.add @title,nil
    render :index
  end
  def jixing
    @yaopins = Yaopin.newest.where(:jixing=>params[:jixing]).page(params[:page] || 1).per(100)
    @title = params[:jixing]

    breadcrumbs.add :jixing,nil
    breadcrumbs.add @title,nil
    render :index
  end
  def leibie
    @yaopins = Yaopin.newest.where(:leibie=>params[:leibie]).page(params[:page] || 1).per(100)
    @leibie = params[:leibie]
    @title = params[:leibie]

    breadcrumbs.add :leibie,nil
    breadcrumbs.add @title,nil
    render :index
  end
  def manage
    @yaopins = Yaopin.page(params[:page] || 1).per(100)
  end

  # GET /yaopins/1
  # GET /yaopins/1.json
  def show
    @yaopin = Yaopin.find(params[:id])
    #logger.debug @yaopin
    @q = @yaopin.wenhao

    @drug = @yaopin.drug
    @yaopins = @drug.yaopins.newest.limit(10).all if @drug.yaopins_count.present? && @drug.yaopins_count > 1

    breadcrumbs.add @drug.name,"/yaopin/#{@drug.to_param}/pihao" if @drug.present?
    breadcrumbs.add @yaopin.wenhao,nil
    session["user_return_to"] = request.url
    #render [0,1].sample > 0 ? "show" : "show1"
    render "show_3col"
  end

  # GET /yaopins/new
  # GET /yaopins/new.json
  def new
    @yaopin = Yaopin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yaopin }
    end
  end

  # GET /yaopins/1/edit
  def edit
    @yaopin = Yaopin.find(params[:id])
  end

  # POST /yaopins
  # POST /yaopins.json
  def create
    @yaopin = Yaopin.new(params[:yaopin])

    respond_to do |format|
      if @yaopin.save
        format.html { redirect_to @yaopin, notice: 'Yaopin was successfully created.' }
        format.json { render json: @yaopin, status: :created, location: @yaopin }
      else
        format.html { render action: "new" }
        format.json { render json: @yaopin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /yaopins/1
  # PUT /yaopins/1.json
  def update
    @yaopin = Yaopin.find(params[:id])

    respond_to do |format|
      if @yaopin.update_attributes(params[:yaopin])
        format.html { redirect_to @yaopin, notice: 'Yaopin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @yaopin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yaopins/1
  # DELETE /yaopins/1.json
  def destroy
    @yaopin = Yaopin.find(params[:id])
    @yaopin.destroy

    respond_to do |format|
      format.html { redirect_to yaopins_url }
      format.json { head :no_content }
    end
  end
  private
  def init_breadcrumbs
    super
    breadcrumbs.add :yaopin,yaopins_url unless action_name == 'show'
  end

end

app/helpers/yaopins_helper.rb
# -*- encoding : utf-8 -*-
module YaopinsHelper
  def yaopin_column k,v
    if respond_to? "yaopin_#{k}"
      send "yaopin_#{k}",v
    else
      v.is_a?(String) ? v.gsub(/；|;/,'<br />').html_safe : v
    end
  end
  def yaopin_changjia_name v
    link_to v,"/pihao/search?q=#{CGI.escape v}"
  end
  def yaopin_jixing v
    link_to v,jixing_url(v)
  end
  def yaopin_leibie v
    link_to v,leibie_url(v)
  end
end

app/views/yaopins/_comments.html.haml
#comments
  -comments = obj.comment_threads.includes([:commentable,:user])
  -if comments.empty?
  -else
    %strong 网友跟贴
    %ul.comments
      -comments.each do |c|
        %li
          %cite #{c.author_name}
          %date.muted #{c.created_at.to_formatted_s(:db)}
          %p #{c.body}

app/views/yaopins/_table.html.haml
%table.table.table-bordered.yaopin
  %tr
    %th.pihao 批号
    -unless @hide_yaoming
      %th.name 名称
    -#%th.benweima 本位码
    -#%th 商品名
    %th.changjia 厂家
    %th.jixing 剂型
    %th.leibie 类别

  - @yaopins.each do |yaopin|
    %tr
      %td=link_to yaopin.wenhao,yaopin
      -unless @hide_yaoming
        %td
          =link_to yaopin.name,yao_url(yaopin) unless yaopin.name.nil?
          -unless yaopin.en.nil? or yaopin.en == '－－－－'
            -#%br
            -l = 50 - yaopin.name.length
            -if yaopin.en.length < l
              =yaopin.en
            -else
              %abbr{:title=>yaopin.en}= yaopin.en.truncate(l)

      %td= yaopin.changjia_name
      %td=link_to yaopin.jixing,jixing_url(yaopin.jixing) unless yaopin.jixing.nil?
      %td=yaopin.leibie unless yaopin.leibie.nil?

app/views/yaopins/edit.html.haml
%h1 Editing yaopin

= render 'form'

= link_to 'Show', @yaopin
\|
= link_to 'Back', yaopins_path

app/views/yaopins/new.html.haml
%h1 New yaopin

= render 'form'

= link_to 'Back', yaopins_path

app/views/yaopins/show.html.haml
-title [@yaopin.wenhao,[@yaopin.shangpin_name,@yaopin.name,@yaopin.changjia_name].compact.join(',')].join("——"),@yaopin.wenhao,false
-keywords [@yaopin.wenhao,@yaopin.shangpin_name,@yaopin.name,@yaopin.changjia_name].compact
-@desc = "#{@yaopin.wenhao}，名称#{@yaopin.name}，由位于#{@yaopin.changjia_guojia}#{@yaopin.changjia_dizhi}的#{@yaopin.changjia_name}生产，批准于#{@yaopin.pizhunri}。为#{@yaopin.jixing}#{@yaopin.leibie},规格为#{@yaopin.guige}。"
-meta_desc @desc
-@title_suffix = ""
-@hide_ad_before = true
-#-@hide_adside = true
-@noliubai = true
-@spans = 9
=debug @yaopin if params[:debug]
-#= render :partial => ['details_a','details_b'].sample
= render :partial => 'details_a'

%hr
  .btn-group.align-center
    <a href="/" rel="nofollow" class="btn">网站首页</a>
    <a href="/yaopin/#{CGI.escape @yaopin.name}/pihao" rel="nofollow" class="btn">#{@yaopin.name}</a>
-if @yaopins.present?    
  %h2 更多#{@yaopin.name}    
  .yaopins
    -@yaopins.each do |r|
      =link_to r.wenhao[4,9],r,:title=>r.wenhao unless r.id == @yaopin.id
  <br />
  <a href="/yaopin/#{CGI.escape @yaopin.name}/pihao" rel="nofollow">更多</a>
%hr
  
= render :partial => 'comments',locals:{:obj=>@yaopin}
%strong 发表留言
= render :partial => 'comment_form',locals:{:obj=>@yaopin}
%hr

-#= link_to 'Edit', edit_yaopin_path(@yaopin),:class=>"btn" if can? :edit,@yaopin
-#-cache ['others-by-changjia_name',@yaopin.changjia_name],:expires_in=>1.day do
  -#-results = Yaopin.by_changjia(@yaopin.changjia_name).slimit(10).search
  -#-if results.present?
    -#%h3 #{@yaopin.changjia_name}生产的其它药品
    -#%p.stats 共找到#{results.total_entries}项结果
    -#%ul.oxox
      -#-results.each do |r|
        -#%li
          -#=link_to r.wenhao,r
          -#-if r.name
            -#%small=link_to r.name,"/#{CGI.escape(r.name)}"
    

-#=slotf

-#-content_for :sidebar do
  -#=ubaidu 1263949,"jx-home-side"
  -#=usogou 192407
  -#<script type="text/javascript">alimama_pid="mm_10894158_3382349_11501603";alimama_width=200;alimama_height=200;</script><script src="http://a.alimama.cn/inf.js" type="text/javascript"></script>
-content_for :footer do
  =javascript_tag "track_data('pihao','#{@yaopin.id}','#{request.referer.present? ? CGI.escape(request.referer).reverse : ""}')" if Rails.env.production?

app/views/yaopins/show_3col.html.haml
-title [@yaopin.wenhao,[@yaopin.shangpin_name,@yaopin.name,@yaopin.changjia_name].compact.join(',')].join("——"),@yaopin.wenhao,false
-keywords [@yaopin.wenhao,@yaopin.shangpin_name,@yaopin.name,@yaopin.changjia_name].compact
-@desc = "#{@yaopin.wenhao}，名称#{@yaopin.name}，由位于#{@yaopin.changjia_guojia}#{@yaopin.changjia_dizhi}的#{@yaopin.changjia_name}生产，批准于#{@yaopin.pizhunri}。为#{@yaopin.jixing}#{@yaopin.leibie},规格为#{@yaopin.guige}。"
-meta_desc @desc
-@title_suffix = ""
-@hide_ad_before = true
-#-@hide_adside = true
-@noliubai = true
-@spans = 9
=debug @yaopin if params[:debug]
-#= render :partial => ['details_a','details_b'].sample
.row-fluid
  .span3.sidebar
    -scopes = %w(kad yaofangcn dada360 jxdyf)
    -@items = @drug.items.select("items.scope,price,url").all.sort{|a,b| scopes.index(a.scope)<=>scopes.index(b.scope)}
    -@items.reject!{|a| a.scope != 'kad'} if @items.collect{|r| r.scope}.include?("kad")
    -@items.reject!{|a| a.scope == 'dada360'}
    -if @items.present?
      .price-widget
        %h2 #{@drug.name}价格
        %table.table
          -@items.each do |item|
            %tr
              %td
                =eval("item_link_#{item.scope}(item)")
              %td
                %span.price=number_to_currency(item.price)
    .sidelink=ubaidu 1420650,'jx-yaopin-sidelink'
    -#-if @items.empty?
      -#%h3.small #{@yaopin.name}购买链接
      -#%p
        -#%span 搜索: 
        -#=link_to_360kad @drug.name
  .span9
    = render :partial => 'details_b'

%hr
  .btn-group.align-center
    <a href="/" rel="nofollow" class="btn">网站首页</a>
    <a href="/yaopin/#{CGI.escape @yaopin.name}/pihao" rel="nofollow" class="btn">#{@yaopin.name}</a>
-if @yaopins.present?    
  %h2 更多#{@yaopin.name}    
  .yaopins
    -@yaopins.each do |r|
      =link_to r.wenhao[4,9],r,:title=>r.wenhao unless r.id == @yaopin.id
  <br />
  <a href="/yaopin/#{CGI.escape @yaopin.name}/pihao" rel="nofollow">更多</a>
%hr
  
= render :partial => 'comments',locals:{:obj=>@yaopin}
%strong 发表留言
= render :partial => 'comment_form',locals:{:obj=>@yaopin}
%hr

-#= link_to 'Edit', edit_yaopin_path(@yaopin),:class=>"btn" if can? :edit,@yaopin
-#-cache ['others-by-changjia_name',@yaopin.changjia_name],:expires_in=>1.day do
  -#-results = Yaopin.by_changjia(@yaopin.changjia_name).slimit(10).search
  -#-if results.present?
    -#%h3 #{@yaopin.changjia_name}生产的其它药品
    -#%p.stats 共找到#{results.total_entries}项结果
    -#%ul.oxox
      -#-results.each do |r|
        -#%li
          -#=link_to r.wenhao,r
          -#-if r.name
            -#%small=link_to r.name,"/#{CGI.escape(r.name)}"
    

-#=slotf

-#-content_for :sidebar do
  -#=ubaidu 1263949,"jx-home-side"
  -#=usogou 192407
  -#<script type="text/javascript">alimama_pid="mm_10894158_3382349_11501603";alimama_width=200;alimama_height=200;</script><script src="http://a.alimama.cn/inf.js" type="text/javascript"></script>
-#-content_for :footer do
  -#=javascript_tag "track_data('pihao','#{@yaopin.id}','#{request.referer.present? ? CGI.escape(request.referer).reverse : ""}')" if Rails.env.production?