config/routes.rb
# -*- encoding : utf-8 -*-
Yl::Application.routes.draw do
  themes_for_rails

  constraints(CoSubdomain) do
    root to: "companies#home"
  end
  constraints :subdomain => 'c' do
    root to: "companies#index"
    get '/p-:id' => "companies#province",as: "province"
    resources :companies,path: '' do
      get :all,on: :collection
    end
  end


  get "settings/index"

  resources :shops,path: "yaodian" do
    get "redirect",on: :member
  end


  resources :options


  resources :jibings,:path=>'jibing' do
    member do 
      get 'suggest'
    end
  end

  match "/goto/:class_name/:id"=>'home#goto'
  resources :comments,:only=>%w(index create show)

  resources :entries,:path=>'zhaoshang' do
    collection do 
      get :hot
    end
  end
  match '/archive/:date'=>'home#date',:as=>'date'
  match '/archive'=>'home#archive',:as=>'archive'

  resources :posts,:path=>"news"

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "tools/adsense"
  get "tools/adsense_preview"
  match '/gad'=>'tools#adsense'

  resources :links do
    collection do
      get :manage
    end
  end

  match '/category/:category_id'=>'drugs#category',:as=>"category"
  resources :chengfens,:path=>'chengfen' , :only=>[:index,:show] do
    get :shouzi,:on=>:collection
  end

  resources :categories do
    collection do
      get :manage
    end
  end

  # match '/chengfen/:name'=>"yaopins#chengfen",:as=>"chengfen"



  # match '/yaoming/:name'=>"yaopins#name",:as=>"name"
  match '/jixing/:jixing'=>"yaopins#jixing",:as=>"jixing"
  match '/leibie/:leibie'=>"yaopins#leibie",:as=>"leibie"
  resources :yaopins,:path=>'pihao' do
    collection do
      get :manage
      get :auto_complete
      get :search
      get :map
    end
    member do
      post :track
    end
  end

  # authenticated :user do
    # root :to => 'home#index'
  # end

  devise_for :users
  resources :users, :only => [:show, :index]
  get '/profile/edit'=>"users#edit_profile",:as=>'edit_profile'
  put '/profile'=>"users#update_profile",:as=>'update_profile'
  match '/:id/%e8%af%b4%e6%98%8e%e4%b9%a6'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  match '/:id/%E8%AF%B4%E6%98%8E%E4%B9%A6'=>"drugs#shuomingshu"
  resources :drugs,:path=>'yaopin' do
    collection do
      get :manage
      get :shouzi
      get :search
      get :desc
      get :desc_preview
    end
    member do
      get :pihao
      post :track
      # get :shuomingshu
    end
  end

  match '/bdapp(/:action(/:id))'=>"bdapp"
  match 'sitemap' => 'home#sitemap'
  match 'flush' => 'home#flush'
  match 'index' => 'home#index'
  match 'redirect' => 'home#redirect',as: 'redirect'
  match ':action' => "home",:constraints=>{:action=>/sitemap|flush|souyao|stats|mmseg|test|redirect|chaxun/}
  resque_constraint = lambda do |request|
    Rails.env.development? or 
    (request.env['warden'].authenticate? and
      request.env['warden'].user.has_role?(:admin))
  end
  constraints resque_constraint do
    match '/settings(/:action(/:id))'=>"settings"
    mount Resque::Server.new, :at => "/resque"
  end
  #match '/(ask|wiki)/:id' => "posts#show",as: "po"
  match '/:act/:id' => "posts#show",:constraints=>{:act=>/news|ask|wiki/},as: :po
  #match '/ask/:id' => "posts#show",as: :ask
  #match '/wiki/:id' => "posts#show",as: :wiki

  match '/:id'=>"drugs#show",:as=>"show_yao"

  #match '/:id/说明书'=>"drugs#shuomingshu",:as=>"shuomingshu"#,:constraints=>{:id=> /.+%E8%AF%B4%E6%98%8E%E4%B9%A6/}
  root :to => "home#index"
match "syncs/:type/new" => "syncs#new", :as => :sync_new
match "syncs/:type/callback" => "syncs#callback", :as => :sync_callback

end

app/models/company.rb
#encoding: utf-8
class Company < ActiveRecord::Base
  belongs_to :city
  belongs_to :province
  attr_accessible :address, :name, :short, :yaopins_count,:city_id,:province_id
  has_many :yaopins
  def detect_data
    str = [name , address].join(',')
    hash = Province.detect_province_and_city(str)
    self.city = hash[:city]
    self.province = hash[:province]
    self.short = name.gsub(/\(有限责任公司\)|\(有限公司\)|有限责任公司|股份有限公司|有限公司/,'')
    #self.yaopins_count = Yaopin.where()
  end
  def self.autogen
    Yaopin.group(:changjia_name).select('changjia_name,changjia_dizhi').each do |yp|
      import_from(yp.changjia_name,yp.changjia_dizhi)
    end
  end
  def self.import_from name,address
    return if name == '----'
    c = new(name: name,address: address)
    c.detect_data
    c.yaopins_count = Yaopin.where(changjia_name: name).count
    c.save
    Yaopin.where(changjia_name: name).update_all(company_id: c.id)
    c
  end
end

app/controllers/companies_controller.rb
#encoding: utf-8
class CompaniesController < ApplicationController
  load_and_authorize_resource :only=>%w(new edit update create destroy)
  before_filter :_init
  before_filter :_bc,only: %w(all province show)
  def _init
    @title_suffix = ""
    @hide_subnav = true
    @hide_foot = true
  end
  def _bc
    breadcrumbs.add "制药企业大全",root_url(subdomain: 'c')
  end
  def index
    @companies = Company.order('yaopins_count desc').includes(:province,:city).limit(50)
    breadcrumbs.add "制药企业大全",nil
  end
  def all
    @companies = Company.includes(:province,:city).page(params[:page])
  end
  def province
    @province = Province.where(pinyin: params[:id]).first
    @companies = Company.where(province_id: @province).includes(:city).page(params[:page])
    breadcrumbs.add @province.short_name,(params[:page].nil? ? nil : province_url(@province))
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])
    @pihao = @company.yaopins.page(params[:page])
    breadcrumbs.add @company.short,(params[:page].nil? ? nil : company_url(@company))

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :short
    = f.association :city
    = f.association :province
    = f.input :address
    = f.input :yaopins_count

  .form-actions
    = f.button :submit

app/views/companies/all.html.haml
-title "制药企业名录"

%table.table
  %tr
    %th 名称
    %th 所在
    %th 注册药品数量

  - @companies.each do |company|
    %tr
      %td= link_to company.short,company
      %td
        = company.province.short_name if company.province.present?
        = company.city.name if company.city.present?
      %td= company.yaopins_count

.clearfix
=xpaginate @companies
.clearfix

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
-title "制药企业大全"
-provs = Province.all_in_neidi
-if provs.present?
  .well
    -provs.each do |p|
      =link_to p.short_name,province_url(p.pinyin),class: ""
%h2 制药企业排名
%table.table
  %tr
    %th 名称
    %th 所在
    %th 注册药品数量

  - @companies.each do |company|
    %tr
      %td= link_to company.short,company
      %td
        = company.province.short_name if company.province.present?
        = company.city.name if company.city.present?
      %td= company.yaopins_count

%br

=link_to "全部制药公司名录",all_companies_url

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/province.html.haml
-title "#{@province.short_name}的制药企业"
%table.table
  %tr
    %th 名称
    %th 所在
    %th 注册药品数量

  - @companies.each do |company|
    %tr
      %td= link_to company.short,company
      %td
        = company.city.name if company.city.present?
      %td= company.yaopins_count

.clearfix
=xpaginate @companies
.clearfix

app/views/companies/show.html.haml
-title t('.title',short: @company.short,name: @company.name),@company.short
-@hide_ad_before = true

%ul.unstyled.attrs
  %li
    %b 公司全称:
    = @company.name
  %li
    %b 所在:
    -if @company.province.present?
      =@company.province.short_name
      = @company.city.name if @company.city.present?
  %li
    %b 地址:
    = @company.address
  %li
    %b 注册药品数:
    = @company.yaopins_count

%p
  -if can? :edit,@company
    = link_to 'Edit', edit_company_path(@company)
    \|
  = link_to '返回', companies_path
-unless @pihao.empty?
  %h2 #{@company.name}注册生产的药品
  = render :partial => 'yaopins/list_in_company',:locals=>{:results=>@pihao}
  =xpaginate @pihao
-else
  没有相应的记录